import type { DirectionMeta, District, Measure, ScoreVector } from './types';

export const BUDGET_LIMIT = 100;
export const REQUIRED_DECISIONS = 5;

export const DIRECTIONS: DirectionMeta[] = [
  {
    id: 'transport',
    label: 'Транспорт',
    fullLabel: 'Транспорт',
    shortLabel: 'ТР',
    color: '#3478f6',
  },
  {
    id: 'ecology',
    label: 'Экология',
    fullLabel: 'Озеленение и экология',
    shortLabel: 'ЭК',
    color: '#2aa876',
  },
  {
    id: 'social',
    label: 'Соцсфера',
    fullLabel: 'Социальная инфраструктура',
    shortLabel: 'СО',
    color: '#8854d0',
  },
  {
    id: 'safety',
    label: 'Безопасность',
    fullLabel: 'Безопасность',
    shortLabel: 'БЗ',
    color: '#f08c46',
  },
  {
    id: 'services',
    label: 'Сервисы',
    fullLabel: 'Городские сервисы',
    shortLabel: 'СВ',
    color: '#d85273',
  },
];

const score = (
  transport: number,
  ecology: number,
  social: number,
  safety: number,
  services: number,
): ScoreVector => ({ transport, ecology, social, safety, services });

export const DISTRICTS: District[] = [
  {
    id: 'esil',
    name: 'Есильский район',
    shortName: 'Есиль',
    baseline: score(62, 74, 66, 72, 78),
    sensitivity: score(0.8, 0.75, 0.8, 0.75, 0.7),
  },
  {
    id: 'saryarka',
    name: 'район Сарыарқа',
    shortName: 'Сарыарқа',
    baseline: score(48, 47, 57, 54, 56),
    sensitivity: score(1.2, 1.15, 1.05, 1.1, 1.05),
  },
  {
    id: 'almaty',
    name: 'район Алматы',
    shortName: 'Алматы',
    baseline: score(55, 54, 62, 63, 60),
    sensitivity: score(1.05, 1, 0.95, 0.9, 1),
  },
  {
    id: 'baikonyr',
    name: 'район Байқоңыр',
    shortName: 'Байқоңыр',
    baseline: score(45, 50, 54, 48, 51),
    sensitivity: score(1.25, 1.15, 1.15, 1.2, 1.1),
  },
  {
    id: 'nura',
    name: 'район Нұра',
    shortName: 'Нұра',
    baseline: score(64, 63, 59, 67, 69),
    sensitivity: score(0.85, 0.9, 1.1, 0.9, 0.85),
  },
];

export const MEASURES: Measure[] = [
  {
    id: 'adaptive-lights',
    title: 'Адаптивные светофоры',
    description: 'AI-фазы на 46 перекрёстках сокращают задержки в часы пик.',
    direction: 'transport',
    cost: 17,
    duration: '6–9 мес.',
    coverage: 'citywide',
    impact: score(9, 2, 1, 2, 2),
    tradeoff: 'Эффект зависит от качества дорожных датчиков.',
    badge: 'Быстрый эффект',
  },
  {
    id: 'rapid-bus',
    title: 'Экспресс-коридоры для автобусов',
    description: 'Выделенные полосы связывают три района с деловым центром.',
    direction: 'transport',
    cost: 24,
    duration: '12–18 мес.',
    coverage: ['saryarka', 'almaty', 'baikonyr'],
    impact: score(13, 6, 3, 1, -1),
    tradeoff: 'На этапе запуска сокращается полоса для личного транспорта.',
    badge: 'Макс. влияние',
  },
  {
    id: 'school-routes',
    title: 'Безопасные школьные маршруты',
    description: 'Новые переходы, велополосы и успокоение трафика у школ.',
    direction: 'transport',
    cost: 13,
    duration: '4–6 мес.',
    coverage: ['almaty', 'nura', 'esil'],
    impact: score(5, 2, 4, 6, 0),
    tradeoff: 'Локальные ограничения скорости увеличат время части поездок.',
  },
  {
    id: 'green-belt',
    title: 'Зелёный пояс «Салқын қала»',
    description: 'Теневые аллеи и 18 000 устойчивых к климату деревьев.',
    direction: 'ecology',
    cost: 21,
    duration: '18–24 мес.',
    coverage: ['saryarka', 'baikonyr', 'almaty'],
    impact: score(0, 13, 3, 1, 1),
    tradeoff: 'Полный эффект проявится через несколько сезонов.',
    badge: 'Долгий эффект',
  },
  {
    id: 'smart-irrigation',
    title: 'Умный полив парков',
    description: 'Датчики влажности снижают расход воды и гибель посадок.',
    direction: 'ecology',
    cost: 12,
    duration: '5 мес.',
    coverage: 'citywide',
    impact: score(0, 8, 0, 0, 3),
    tradeoff: 'Нужна ежегодная калибровка датчиков.',
    badge: 'Экономия воды',
  },
  {
    id: 'eco-yards',
    title: 'Эко-дворы без асфальтовых островов',
    description: 'Дождевые сады, тень и игровые зоны в 22 дворах.',
    direction: 'ecology',
    cost: 15,
    duration: '8–12 мес.',
    coverage: ['saryarka', 'baikonyr'],
    impact: score(0, 9, 5, 2, 1),
    tradeoff: 'Часть парковочных мест потребуется перенести.',
  },
  {
    id: 'mobile-clinics',
    title: 'Мобильные кабинеты здоровья',
    description: 'Выездная диагностика в районах с низкой доступностью услуг.',
    direction: 'social',
    cost: 18,
    duration: '3–5 мес.',
    coverage: ['saryarka', 'baikonyr', 'nura'],
    impact: score(0, 0, 10, 1, 4),
    tradeoff: 'Потребуется устойчивый график врачебных смен.',
    badge: 'Запуск за сезон',
  },
  {
    id: 'schools-renewal',
    title: 'Обновление перегруженных школ',
    description: 'Модульные корпуса и STEM-лаборатории для 3 200 учеников.',
    direction: 'social',
    cost: 23,
    duration: '12–16 мес.',
    coverage: ['almaty', 'nura', 'esil'],
    impact: score(1, 0, 13, 3, 1),
    tradeoff: 'Строительные работы временно усложнят логистику школ.',
    badge: 'Высокий охват',
  },
  {
    id: 'sport-hubs',
    title: 'Инклюзивные спорт-хабы',
    description: 'Доступные площадки и бесплатные секции в пяти кварталах.',
    direction: 'social',
    cost: 14,
    duration: '7–10 мес.',
    coverage: 'citywide',
    impact: score(0, 1, 8, 3, 1),
    tradeoff: 'Эксплуатационные расходы сохранятся после запуска.',
  },
  {
    id: 'smart-lighting',
    title: 'Умное уличное освещение',
    description: 'LED-светильники с адаптивной яркостью на тёмных маршрутах.',
    direction: 'safety',
    cost: 11,
    duration: '4–6 мес.',
    coverage: ['saryarka', 'baikonyr', 'almaty'],
    impact: score(0, -1, 1, 8, 2),
    tradeoff: 'Нужна настройка, чтобы снизить световое загрязнение.',
    badge: 'Низкая стоимость',
  },
  {
    id: 'rapid-response',
    title: 'Единый центр реагирования',
    description: 'Объединённая диспетчерская для 112 и коммунальных аварий.',
    direction: 'safety',
    cost: 16,
    duration: '7–9 мес.',
    coverage: 'citywide',
    impact: score(1, 0, 1, 11, 5),
    tradeoff: 'Интеграция старых систем может задержать запуск.',
    badge: 'Городской охват',
  },
  {
    id: 'safe-city',
    title: 'Safe City: прогноз инцидентов',
    description: 'Аналитика городских сигналов для профилактики рисков.',
    direction: 'safety',
    cost: 19,
    duration: '9–12 мес.',
    coverage: ['esil', 'saryarka', 'baikonyr'],
    impact: score(0, 0, -1, 12, 4),
    tradeoff: 'Нужны прозрачные правила приватности и аудита модели.',
  },
  {
    id: 'citizen-superapp',
    title: 'Суперапп «Мой район»',
    description: 'Заявки, статусы работ и городские услуги в одном окне.',
    direction: 'services',
    cost: 9,
    duration: '4–6 мес.',
    coverage: 'citywide',
    impact: score(0, 0, 2, 1, 9),
    tradeoff: 'Нужны офлайн-каналы для жителей без смартфона.',
    badge: 'Лучшее соотношение',
  },
  {
    id: 'utility-twin',
    title: 'Цифровой двойник теплосетей',
    description: 'Прогноз утечек и ремонтов до аварийного отключения.',
    direction: 'services',
    cost: 15,
    duration: '10–14 мес.',
    coverage: ['saryarka', 'almaty', 'baikonyr'],
    impact: score(0, 3, 1, 3, 11),
    tradeoff: 'Точность зависит от полноты схем старых сетей.',
    badge: 'Снижает аварии',
  },
];
